*** TODO Fix horizontal/vertical flipping

#+BEGIN_EXAMPLE
Exception while running jpegtran -flip horizontal -outfile F:\incoming\images\TOGoS\photos\2020\06\2020_06_23\204030-20200623_204030.jpg F:\incoming\images\TOGoS\photos\2020\06\2020_06_23\204030-20200623_204030.jpg
        at togos.picturearchiver4_1.util.SystemUtil.runCommand(SystemUtil.java:32)
        at togos.picturearchiver4_1.ImageManager.jpegtranFlip(ImageManager.java:440)
        ... 42 more
#+END_EXAMPLE

And the result is a zero-byte file.
I can recover the original and do all the steps up to the flip
and then do the flip manually from the command-line, and that works!

Seems like this happens after compressing.

Maybe non-destructive modifications would happen to solve this.

*** TODO Non-destructive modifications

Store a list of modifications (rotations, compression, etc)
so that additional modifications can be performed as losslessly as possible.
e.g. rotate-right,rotate-right,rotate-right,rotate-right,compress,compress,compress
is the same as just compressing to the third compression level.

This could replace the more special-purpose and hackey remembering of the current compression level.

*** TODO Option to publish/copy URN of picture to clipboard

*** TODO Write documentation

Otherwise I'm going to forget how my own program works lol

e.g. how does -archive-map work

*** TODO Show files in archive-mapped directories

These should be read-only; don't allow modifications.  Maybe allow deleting, though?

Maybe have 'archived' grayed out (instead of yellow) to indicate it's not changeable.

*** TODO Loud indicator for very large images

Maybe a bright red border or something.
